version: '3'
services:
    jenkins2:
        user: root
        image: jenkins/docker
        build:
                context: dockerjenkins
        ports:
            - 9000:8080
            - 50000:50000
        container_name: jenkins
        volumes:
            - $PWD/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - net
networks:
    net:
